nodes:
  - node: uno@uno
    role: master
  - node: dos@dos
    role: master

services:
  nginx:
    image: nginx:latest
    restart: on-failure
    privileged: true
    cpus: 0
    disk: 0
    memory: 0
    roles:
      - master
    environment:
      - NAMES=uno_dos
    labels:
      - LABEL=SomeLabel
    ports:
      - port0:
          - container_port: "80"
          - host_port: "0"
          - protocol: "tcp"
          - name: "website"
      - port1:
          - container_port: "90"
          - host_port: "500"

  nginx:
    image: nginx:latest
    restart: on-failure
    privileged: false
    network_mode: host
    cpus: 0
    disk: 0
    memory: 0
    roles:
      - master
    environment:
      - NAMES=uno_dos
    labels:
      - LABEL=SomeLabel
